apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: {{{ truncate ( sanitize .Name ) }}}
  namespace: rhtap-releng-tenant
spec:
  applications: [{{{ truncate ( sanitize .ApplicationName ) }}}]
  origin: ocp-serverless-tenant
  policy: registry-standard
  data:
    mapping:
      components:
      {{{- range $component := .Components }}}
        - name: {{{ $component.ComponentName }}}
          repository: {{{ $component.ImageRepository }}}
          pushSourceContainer: true
      {{{- end }}}
    pyxis:
      secret: {{{ .PyxisSecret }}}
      server: {{{ .PyxisServer }}}
    sign:
      configMapName: "hacbs-signing-pipeline-config-redhatrelease2"
    defaults:
      tags:
        - "{{ git_sha }}"
        - "{{ git_short_sha }}"
        - "{{{ .SOVersion }}}"
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/rh-advisories/rh-advisories.yaml"
    serviceAccountName: {{{ .PipelineSA }}}
    timeouts:
      pipeline: "4h0m0s"
